#ifndef COURSERACLONE_TYPES_FILESTYPES_HPP
#define COURSERACLONE_TYPES_FILESTYPES_HPP

/// @brief Resultados de operaciones de archivo
enum class FileOperationResult
{
    SUCCESS,
    FILE_NOT_FOUND,
    PERMISSION_DENIED,
    CORRUPTION_DETECTED,
    UNKNOWN_ERROR
};

#endif // !COURSERACLONE_TYPES_FILESTYPES_HPP
